# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='问题描述 [HTML]')),
                ('description_md', models.TextField(blank=True, verbose_name='问题描述 [Markdown]')),
                ('input_description', models.TextField(blank=True, verbose_name='输入描述 [HTML]')),
                ('input_description_md', models.TextField(blank=True, verbose_name='输入描述 [Markdown]')),
                ('output_description', models.TextField(blank=True, verbose_name='输出描述 [HTML]')),
                ('output_description_md', models.TextField(blank=True, verbose_name='输出描述 [Markdown]')),
                ('sample_input', models.TextField(blank=True, verbose_name='样例输入')),
                ('sample_output', models.TextField(blank=True, verbose_name='样例输出')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('hint', models.TextField(blank=True, verbose_name='提示 [HTML]')),
                ('hint_md', models.TextField(blank=True, verbose_name='提示 [Markdown]')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('time_limit', models.IntegerField(default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.IntegerField(default=128, verbose_name='内存限制(MB)')),
                ('accept_count', models.IntegerField(default=0, verbose_name='通过数量')),
                ('submit_count', models.IntegerField(default=0, verbose_name='提交数量')),
                ('reserved', models.BooleanField(default=False, verbose_name='预备题目')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(related_name='languages', to='utils.CodeLang')),
            ],
            options={
                'verbose_name': '问题',
                'ordering': ('id',),
                'verbose_name_plural': '问题',
            },
        ),
    ]
