# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('id',), 'permissions': (('CreateProblem', '创建题目'),), 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='reserved',
            field=models.BooleanField(default=True, verbose_name='预备题目'),
        ),
    ]
