# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20170124_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('id',), 'permissions': (('problems.create', '创建题目'), ('problems.update', '更新题目'), ('problems.delete', '删除题目')), 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, verbose_name='题目描述 [HTML]'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description_md',
            field=models.TextField(blank=True, verbose_name='题目描述 [Markdown]'),
        ),
    ]
