# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20170124_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('id',), 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
    ]
