# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20170124_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='reserved',
            field=models.BooleanField(default=True, verbose_name='题目不可见'),
        ),
    ]
