# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170124_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bc_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cf_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hdu_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tc_id',
        ),
    ]
