# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_remove_submission_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='highlighted',
            field=models.TextField(blank=True, verbose_name='高亮源代码'),
        ),
    ]
