# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='语言名称')),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
            },
        ),
    ]
