# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0006_auto_20170125_1218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('public', models.BooleanField(default=True, verbose_name='开放')),
                ('published', models.BooleanField(default=False, verbose_name='发布')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('announcement', models.TextField(blank=True, max_length=500, null=True, verbose_name='公告')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='joined_contests', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(related_name='contests', to='problems.Problem')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
    ]
