# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20170125_1218'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='problems.Problem'),
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together=set([('contest', 'sort')]),
        ),
    ]
