# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170125_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='source',
        ),
    ]
