# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20170125_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['id'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('contest', 'sort'), 'verbose_name': '比赛题目', 'verbose_name_plural': '比赛题目'},
        ),
    ]
