# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20170126_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_contests', to='problems.Problem'),
        ),
    ]
