# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contestsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestsubmission',
            name='problem',
        ),
        migrations.DeleteModel(
            name='ContestSubmission',
        ),
    ]
