# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20170127_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests.ContestProblem')),
            ],
        ),
    ]
