# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:43
from __future__ import unicode_literals

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_remove_submission_contest'),
        ('contests', '0009_contestsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'ordering': ('problem', 'submission'), 'verbose_name': '比赛提交', 'verbose_name_plural': '比赛提交'},
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='submission',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='involved_contest', to='submissions.Submission'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contestsubmission',
            unique_together=set([('problem', 'submission')]),
        ),
    ]
