# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20170127_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestsubmission',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='submission',
        ),
        migrations.DeleteModel(
            name='ContestSubmission',
        ),
    ]
