# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 07:17
from __future__ import unicode_literals

import contests.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0012_auto_20170127_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='队伍名')),
                ('accept_count', models.IntegerField(default=0, verbose_name='通过题数')),
                ('submit_count', models.IntegerField(default=0, verbose_name='提交次数')),
                ('penalty', models.IntegerField(default=0, verbose_name='罚时')),
            ],
            options={
                'ordering': ('contest', 'user'),
                'verbose_name_plural': '比赛账号',
                'verbose_name': '比赛账号',
            },
        ),
        migrations.CreateModel(
            name='ContestStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_count', models.IntegerField(default=0)),
                ('submit_count', models.IntegerField(default=0)),
                ('accept_time', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=models.SET(contests.models.get_sentinel_user), related_name='statistic', to='contests.ContestAccount')),
            ],
            options={
                'verbose_name_plural': '比赛数据',
                'verbose_name': '比赛数据',
            },
        ),
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.AddField(
            model_name='conteststatistic',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='conteststatistic',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='contests.ContestProblem'),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestaccount',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(contests.models.get_sentinel_user), related_name='contest_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='conteststatistic',
            unique_together=set([('contest', 'account', 'problem')]),
        ),
        migrations.AlterUniqueTogether(
            name='contestaccount',
            unique_together=set([('user', 'contest')]),
        ),
    ]
