# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0014_auto_20170129_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestaccount',
            options={'ordering': ('contest', 'date_joined', 'user'), 'verbose_name': '比赛账号', 'verbose_name_plural': '比赛账号'},
        ),
    ]
