# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_auto_20170129_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-id'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
    ]
